[project]
name = 'tokenized-realty'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.realtytoken]
path = 'contracts/realtytoken.clar'
clarity_version = 2
epoch = 2.5

[contracts.iAmm]
path = 'contracts/interfaces/iAmm.clar'
clarity_version = 2
epoch = 2.5

[contracts.iFeeManager]
path = 'contracts/interfaces/iFeeManager.clar'
clarity_version = 2
epoch = 2.5

[contracts.iLiquidity]
path = 'contracts/interfaces/iLiquidity.clar'
clarity_version = 2
epoch = 2.5

[contracts.iEmergencyBrake]
path = 'contracts/interfaces/iEmergencyBrake.clar'
clarity_version = 2
epoch = 2.5

[contracts.iDao]
path = 'contracts/interfaces/iDao.clar'
clarity_version = 2
epoch = 2.5

[contracts.iMetrics]
path = 'contracts/interfaces/iMetrics.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
